### ISSUE TITLE
TypeError: redis.addCommand is not a function, again with this error

### ISSUE THREAD

**Issue by mustzev** [stockholmux/node_redis-rejson#20]
Again with this error, My code:

`
import redis from 'redis'
import rejson from 'redis-rejson'
import { app } from './app.js'

export default async function initRedis() {
   rejson(redis)
   const client = redis.createClient()
   client.on('error', err => console.log('Redis Client Error', err))
   await client.connect()
   app.context.redis = client
}
`
and I am calling this initRedis function in my server app.js.

The error:
`
[nodemon] restarting due to changes...
[nodemon] starting `node app.js`
Server running at http://localhost:9000
(node:14036) UnhandledPromiseRejectionWarning: TypeError: redis.addCommand is not a function
    at D:\Codes\Javascript\React Koa\backend\node_modules\redis-rejson\index.js:5:11
    at Array.forEach (<anonymous>)
    at addReJSONModule (D:\Codes\Javascript\React Koa\backend\node_modules\redis-rejson\index.js:4:8)
    at initRedis (file:///D:/Codes/Javascript/React%20Koa/backend/redis.js:6:4)
    at file:///D:/Codes/Javascript/React%20Koa/backend/app.js:16:1
    at ModuleJob.run (internal/modules/esm/module_job.js:170:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14036) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14036) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

My redis client is working fine executing the default commands otherwise without the `rejson(redis)` line.
What could have gone wrong? Please, check it out.

I am also facing the `redis.addCommand is not a function` error when I try creating the redis client without the whole async block. But redis client doesn't respond and hangs on basic commands in that case.

Versions:
`
node.js: v14.17.4,
"redis": "^4.0.0-rc.0",
"redis-rejson": "^1.0.0",
`

**Comment by Polhus** [comment]
+1. I have exactly the same error `redis.addCommand is not a function`

**Comment by jitheshkt** [comment]
+1. I have exact same error `redis.addCommand is not a function` even with the basic demo provided in the project README.

**Comment by stockholmux** [comment]
Looks like node_redis was re-written in typescript (🙄) and they removed a bunch of stuff. Try pegging the node_redis version to v3. Or appealing to the folks over in node_redis to fix the API for support in the more recent versions.

I don't have anything to do with Redis in my day job anymore, so I'm open to PRs.

**Comment by jitheshkt** [comment]
Thanks for the quick reply. Yes, downgrading the Redis library to stable `3.1.2` fixed the issue.

**Comment by subhamsinha8** [comment]
Hello, I have the following configuration and getting error for client.json_set and client.json_get (Property 'json_set' does not exist on type 'RedisClient'). I am surely missing something out but don't know for sure. Any idea ?
"redis": "^3.1.2", "redis-rejson": "^1.0.0"

**Comment by PamelaRamirezA** [comment]
> Thanks for the quick reply. Yes, downgrading the Redis library to stable `3.1.2` fixed the issue.

Thank u so much!! this solved my problem!!! now, 2 years later than 3.1.2 version released date...
