### ISSUE TITLE
Getting an error setting a json object

### ISSUE THREAD

**Issue by c0debreaker** [stockholmux/node_redis-rejson#3]
Here is my code

```js
const myObject = {"name": "ronneil", "last": "camara"};
client.json_set('myKey', '.', myObject, function(err) {
  console.log("------------->>> ERROR ENCOUNTERED <<< -------------")
  console.log(err)
});
```

and here is the output on the terminal
```js
node_redis: Deprecated: The JSON.SET command contains a argument of type Object.
This is converted to "[object Object]" by using .toString() now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.
------------->>> ERROR ENCOUNTERED <<< -------------
{ ReplyError: ERR JSON lexer error SPECIAL_EXPECTED at position 25
    at parseError (/Users/rcamara/repos/redis-exer/node_modules/redis-parser/lib/parser.js:193:12)
    at parseType (/Users/rcamara/repos/redis-exer/node_modules/redis-parser/lib/parser.js:303:14)
  command: 'JSON.SET',
  args: [ 'myKey', '.', { name: 'ronneil', last: 'camara' } ],
  code: 'ERR' }
```

Also, how do we specify expiration now?

**Comment by stockholmux** [comment]
You have to serialize the object, à la `JSON.stringify({"name": "ronneil", "last": "camara"})`. If you notice in the error output your object is is being sent as `[object Object]`.

Expiry is in another command: `TTL` or `PTTL`

**Comment by c0debreaker** [comment]
Thanks a lot!

**Comment by c0debreaker** [comment]
That is really nice! Thank you so much!!!

**Comment by mschipperheyn** [comment]
If you are considering using straight `JSON.stringify` and `JSON.parse` with Redis, it's useful to read this thread https://github.com/NodeRedis/node_redis/issues/798 to avoid problems with hashing your data.
