### ISSUE TITLE
TypeError: redis.addCommand is not a function

### ISSUE THREAD

**Issue by Muntzer** [stockholmux/node_redis-rejson#6]
Hi, 

I get this errror:

TypeError: redis.addCommand is not a function
    at D:\RedisPoc\node_modules\redis-rejson\index.js:5:11
    at Array.forEach (<anonymous>)
    at addReJSONModule (D:\RedisPoc\node_modules\redis-rejson\index.js:4:8)
    at Object.<anonymous> (D:\RedisPoc\config\redis.js:18:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)

With:

Redis 5.0.0
"redis": "^2.8.0",
"redis-commands": "^1.4.0",
"redis-rejson": "^1.0.0"
npm 6.4.1

How I can resolve it ?

**Comment by stockholmux** [comment]
Can you post your code?

**Comment by Muntzer** [comment]
Hi Kyle,

I have been investigated it.
With the code below
var redis = require('redis');
var rejson = require('redis-rejson');


var redisClient = redis.createClient({
host: "192.168.99.100",
port: 32768
});

redisClient.on("error", function (err) {
console.log("Error RedisClient" + err);
});

redisClient.on('connect', function() {
console.log('RedisClient connected');
});

rejson(redisClient)
module.exports = {redisClient}


I receive this error:
TypeError: redis.addCommand is not a function
    at D:\RedisPoc\node_modules\redis-rejson\index.js:5:11
    at Array.forEach (<anonymous>)
    at addReJSONModule (D:\RedisPoc\node_modules\redis-rejson\index.js:4:8)
    at Object.<anonymous> (D:\RedisPoc\config\redis.js:18:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)

But with this code, don't appear the error:
var redis = require('redis');
var rejson = require('redis-rejson');

rejson(redis)

var redisClient = redis.createClient({
host: "192.168.99.100",
port: 32768
});

redisClient.on("error", function (err) {
console.log("Error RedisClient" + err);
});

redisClient.on('connect', function() {
console.log('RedisClient connected');
});

module.exports = {redisClient}

But, how I can use rejson with the redis client?  Like this redisClient.
json_set( ?

Thanks for your help

Javier,

**Comment by Slooo** [comment]
same problem

**Comment by stockholmux** [comment]
@Muntzer Your second example is correct. You _must_ run `rejson(redis)` *before* creating your client. You would then run the ReJSON commands as normal as methods in the `client` object.

I'm updating the README with more example code to clarify this. 

@Slooo Your problem doesn't actually sound the same as @Muntzer. Open a new issue please.

**Comment by Muntzer** [comment]
@stockholmux , thanks for you help.
